git:
  depth: 1

branches:
  only: 
    - master
    
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: "npm run ci.tslint" 
    - stage: "WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: cd ../demo && tns build ios --bundle --env.uglify
    - language: android
      os: linux
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd ../demo && tns build android --bundle --env.uglify
    - stage: "Build"
      env: 
        - BuildAndroid="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd ../demo && tns build android
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd ../demo && tns build ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-23
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
    - sudo pip install --upgrade pip
    - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable - npm install
    - cd src
    - npm run setup
