android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src

script:


matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: "npm run ci.tslint" 
    - stage: "WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: cd ../demo && tns build ios --bundle --env.uglify && cd ../demo-angular && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd ../demo && tns build android --bundle --env.uglify && cd ../demo-angular && tns build android --bundle --env.uglify --env.aot
    - stage: "Build"
      env: 
        - BuildAndroid="27"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8.9.4
      script:
        - cd ../demo && tns build android && cd ../demo-angular && tns build android
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      script: 
        - cd ../demo && tns build ios && cd ../demo-angular && tns build ios